### ISSUE TITLE
Unity build process description error

### ISSUE THREAD

**Issue by alexzzzz** [SaladLab/Unity3D.IncrementalCompiler#1]
> Unity3D makes three projects from Assets directory if your project has only C# sources

It makes four. The forth one is Assembly-CSharp-Editor-firstpass.dll which contains scripts from all the Editor folders located in Plugins, Standard Assets and Pro Standard Assets folders.

> These projects will be built successively and Unity3d cannot build these concurrently because they depends on previous projects.

This forth Assembly-CSharp-Editor-firstpass.dll can be (and actually is) compiled simultaneously with Assembly-CSharp.dll since they don't reference one another.

Compilation stages:
1. Assembly-CSharp-firstpass.dll
2. Assembly-CSharp.dll + Assembly-CSharp-Editor-firstpass.dll
3. Assembly-CSharp-Editor.dll

Dependency graph: https://dl.dropboxusercontent.com/u/102171874/Unity%20Dependencies.png

**Comment by veblush** [comment]
Thanks for mentioning things that I missed! (document will be updated as you said)
Also appreciate your work about C# 6 adapter for Unity3d.
