### ISSUE TITLE
Latest version causes virus alert on G-DATA Gen:Heur.MSIL.Krypt.2

### ISSUE THREAD

**Issue by Zireael07** [SaladLab/Unity3D.IncrementalCompiler#10]
The earlier versions were fine. What gives?

**Comment by veblush** [comment]
Thanks for reporting. Virustotal says 9 antivirus softwares reports it is a malware. It must be a false positive and just submit this issue to Avira and BitDefender. This is second time and I need to figure out why they detect it as a malware and how to avoid it.

**Comment by veblush** [comment]
Please try the [latest release](https://github.com/SaladLab/Unity3D.IncrementalCompiler/releases/tag/v1.2.8).

**Comment by sslavchev** [comment]
We use latest version, this problem is not solved. Please fix this as soon is possible. Problem is with reading of generated C++ exe files. We have problems with your antivirus package, When build our exe files with included in resource file Version information every time antivirus delete file and trowing alert for virus Gen:Heur:MSIL.Krypt.2.  Also exclusion not working.

**Comment by SugoiDev** [comment]
@sslavchev this repo is no longer being actively developed. The developer has been missing for a while now.

If you're on Unity 2018+, you can try the latest official incremental compiler. Check out [the thread here](https://forum.unity.com/threads/unity-incremental-c-compiler.523993/)

If you're stuck with older Unitys, you can try [alexzzzz's compiler](https://bitbucket.org/alexzzzz/unity-c-5.0-and-6.0-integration/). It's not incremental, but it's faster than the stock one (and you can use C#7.2+ features).

**Comment by sslavchev** [comment]
The problem is with Microsoft Visual Studio 2010. My be good idea is to you check what happens with description of our virus definition. I'm trying SpyHunter and Trend Micro they cannot find virus in my compilet binary file.
