### ISSUE TITLE
Not working on Unity 5.1.2p2

### ISSUE THREAD

**Issue by jagt** [SaladLab/Unity3D.IncrementalCompiler#2]
Hi,

I've tried this project with Unity 5.1.2 and it seems it's reporting a error like this:

```
TypeLoadException: Could not load type 'UnityEditor.Modules.CSharpCompiler' from assembly 'UnityEditor, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
UnityEditor.Scripting.ScriptCompilers.CreateCompilerInstance (MonoIsland island, Boolean buildingForEditor, BuildTarget targetPlatform, Boolean runUpdater) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilers.cs:93)
```

Any idea how this happens? Thanks!
Very exciting to have a tool like this, and if this works it would help us greatly :)

**Comment by veblush** [comment]
Thanks for reporting error. It can be solved if you unblock zip file before decompressing ths file. I added FAQ section at [readme](https://github.com/SaladLab/Unity3D.IncrementalCompiler) to address this problem.

**Comment by jagt** [comment]
@veblush Thanks for the quick response.
May I ask what does 'unblock zip file' mean... I must be missing something because I can't relate this to anything I've done before... Can you give a example or a link? Thanks a lot!

**Comment by veblush** [comment]
[How to: Unblock a downloaded file to avoid security warnings](https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/) will help you.

**Comment by jagt** [comment]
Thanks, I'll try this out and let you know if it works soon :)
