### ISSUE TITLE
Virus warning

### ISSUE THREAD

**Issue by hyperretro** [SaladLab/Unity3D.IncrementalCompiler#8]
Avira antivirus gives a trojan alert for the "IncrementalCompiler.exe" file. This makes it impossible to install the library.

**Comment by veblush** [comment]
Thanks for report! I just  analyzed 1.2.5 package files using VirusTotal and here is [the result](https://www.virustotal.com/en/file/9efa6232104442f8f0c6df87408b668844854794d7e1e7ce62f64158fe6990b0/analysis/1465861515/), 2 of 53 say it is `Trojan.Dropper` but I think it is a false positive and submit this issue  to Avira.

**Comment by veblush** [comment]
Here comes the result of issue from Avira.

> The file 'Compiler/IncrementalCompiler.exe' has been determined to be 'FALSE POSITIVE'.
> In particular this means that this file is not malicious but a false alarm.
> Detection is removed from our virus definition file (VDF) with the version: 8.12.99.134.

It's safe to use but you need to wait for next update of Avira.

**Comment by Godefroy** [comment]
Same issue with Windows Defender.
