### ISSUE TITLE
Force full recompilation to workaround stale cache in situations where it is impossible for the compiler to know the cache is stale

### ISSUE THREAD

**Issue by SugoiDev** [SaladLab/Unity3D.IncrementalCompiler#9]
Sometimes the cache can get stale (especially with indirect cyclic dependencies and constant strings) and it would be nice to have a  function to call (via a menu item or a button) to force a recompilation.

I've had to make a random edit to scripts a few times to force its pass to be recompiled and thought that maybe others will face this as well.

One example I came across that causes the cache to get stale is the following:

* have a normal class with a **constant** string representing a path
* have an editor class reference that path to auto-generate some code in it
* change the path in the normal class

This will recompile the normal assembly, but not the editor assembly, so it will still have the old constant reference.

The reason this happens is that when we access a const string in AssemblyA from AssemblyB, AssemblyB will have the const string's value simply pasted into it (there's no reference at all to AssemblyA). Because of this, when we change the constant in AssemblyA, there's no way for the compiler to know that AssemblyB must be recompiled.

Further reading on the behavior of constant strings can be found on this article: [Const Strings – a very convenient way to shoot yourself in the foot](http://www.stum.de/2009/01/14/const-strings-a-very-convenient-way-to-shoot-yourself-in-the-foot/)

As far as I can see, the only way to work around this is to have a way to manually trigger a recompile whenever we make changes like this.

---

I'm attaching a tiny repro case for this. To use it, unzip to the Assets/ dir.
To check the behavior, let it compile then use **Tools -> Show the String**
Now, open ClassWithConstString and change the constant.
Let it compile and check again **Tools -> Show the String**
It will print the old string value.

[repro.zip](https://github.com/SaladLab/Unity3D.IncrementalCompiler/files/338568/repro.zip)

**Comment by veblush** [comment]
Thanks for your report and good explanation! :+1: 

By default, incremental compiler is configured not to build assemblies aggressively to minimize build time. Could you change `PrebuiltOutputReuse` option to `When No Change` like following?

![image](https://cloud.githubusercontent.com/assets/2793282/16473261/7e0e32ec-3ea6-11e6-8e13-32cb496cb193.png)

It makes the compiler build `Editor` assembly normally whenever something changes. FYI, [UnderTheHood](https://github.com/SaladLab/Unity3D.IncrementalCompiler/blob/master/docs/UnderTheHood.md#reuse-prebuilt-dlls) article might help you for understanding this feature.

**Comment by SugoiDev** [comment]
Thanks for replying! I read your UnderTheHood very carefully when I first got the IncrementalCompiler. Learned quite a bit from it!

I think I can consider this issue closed, as your reply (and further reading the [UnderTheHook](https://github.com/SaladLab/Unity3D.IncrementalCompiler/blob/master/docs/UnderTheHood.md#reuse-prebuilt-dlls) page) made it all clear.

Still, there might be a use-case for having a  "force recompile" button or menu.
Think when you're making many small, incremental changes on some gameplay aspect that has no direct relation to any of your editor scripts. In this case, it's ok for the editor assembly to be stale just so we don't have to wait a few more seconds for the editor assembly to recompile every time we make one of those tiny changes.

Of course we would eventually need to recompile the editor assembly. Then we could trigger a manual recompilation.

Does this make sense to you? Or the compilation times for the Editor assembly wouldn't matter enough to warranty having this extra feature?

For now, I'm using the less aggressive WhenNoChange and I can't say I notice the difference in compilation time.

**Comment by veblush** [comment]
Good to know you made it. 😃

My previous project experience had a major role to make `WhenNoSourceChange` default option. It just used `Editor Assembly` just as tool so it was ok when `WhenNoChange` was turn on. But your project seems not. So It looks better that `WhenNoChange` should be a default option not to make users confuse. Thanks for sharing your environment.

For recompile feature, I agree with you. It will be a handy utility for power users like you.
